kind: PersistentVolume
apiVersion: v1
metadata:
  name: poc-volume-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/persisVolTest
